/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author miko
 */

import entitas.Entitas_Guru;
import groovy.xml.Entity;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import method.Guru_Method;


public class master_guru extends javax.swing.JFrame {
 private DefaultTableModel model;
    List<entitas.Entitas_Guru> listGuru = new ArrayList<>();
    Entitas_Guru eg = new Entitas_Guru();
    Guru_Method sm = new Guru_Method();
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
   
    /**
     * Creates new form master_guru
     */
    public master_guru() {
        initComponents();
      Bersih();
        SiapIsi(false);
        BuatTabel();
        tampil();
        setLocationRelativeTo(this);
        tombolAwal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        cari = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btntambah = new javax.swing.JButton();
        btnsimpan = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        btnkeluar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblguru = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        nip = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        namaguru = new javax.swing.JTextField();
        tempatlahir = new javax.swing.JTextField();
        cbnJabatan = new javax.swing.JComboBox<>();
        GsExit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        telephone = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        alamat = new javax.swing.JTextField();
        tgllahir = new com.toedter.calendar.JDateChooser();
        jenkel = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel11.setText("Data Guru");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 503, 41));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Cari");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 580, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Username");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, -1, -1));
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 460, 150, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Password");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, -1, -1));
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 490, 150, -1));

        cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cariKeyReleased(evt);
            }
        });
        getContentPane().add(cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 580, 340, -1));

        btntambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tambah.png"))); // NOI18N
        btntambah.setText("Tambah");
        btntambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahActionPerformed(evt);
            }
        });

        btnsimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/simpan.png"))); // NOI18N
        btnsimpan.setText("Simpan");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        btnedit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit.png"))); // NOI18N
        btnedit.setText("Edit");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });

        btnhapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hapus.png"))); // NOI18N
        btnhapus.setText("Hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        btnkeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tutup.png"))); // NOI18N
        btnkeluar.setText("Keluar");
        btnkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(btntambah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnsimpan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnedit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnhapus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnkeluar)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btntambah)
                    .addComponent(btnsimpan)
                    .addComponent(btnedit)
                    .addComponent(btnhapus)
                    .addComponent(btnkeluar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, -1, 50));

        tblguru.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblguru.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblguruMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblguru);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 620, 570, 150));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("NIP");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));
        getContentPane().add(nip, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 162, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Telephone");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Nama Lengkap");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));
        getContentPane().add(namaguru, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 255, -1));
        getContentPane().add(tempatlahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 136, 30));

        cbnJabatan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Jabatan -", "guru", "admin", "kepala sekolah" }));
        getContentPane().add(cbnJabatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 100, 30));

        GsExit.setBackground(new java.awt.Color(255, 0, 0));
        GsExit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        GsExit.setText("X");
        GsExit.setToolTipText("keluar");
        GsExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        GsExit.setIconTextGap(1);
        GsExit.setMargin(new java.awt.Insets(2, 2, 2, 2));
        GsExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GsExitActionPerformed(evt);
            }
        });
        getContentPane().add(GsExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 40, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Tempat");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Jenis Kelamin");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Tanggal Lahir");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Jabatan");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));
        getContentPane().add(telephone, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, 150, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Alamat");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));
        getContentPane().add(alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 290, 130));
        getContentPane().add(tgllahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 129, 30));

        jenkel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Laki-laki", "Perempuan" }));
        getContentPane().add(jenkel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 100, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pendaftaran.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -130, 600, -1));

        setBounds(0, 0, 618, 837);
    }// </editor-fold>//GEN-END:initComponents

    private void btntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahActionPerformed
        // TODO add your handling code here:
      
        if(btntambah.getText().equalsIgnoreCase("tambah")){
            btntambah.setText("Batal");
            Bersih();
            SiapIsi(true);
            nip.requestFocus();
            btntambah.setEnabled(true);
            btnsimpan.setEnabled(true);
            btnhapus.setEnabled(false);
            btnedit.setEnabled(false);
            btnkeluar.setEnabled(false);
            cari.setEnabled(false);
        }else{
            btntambah.setText("Tambah");
            Bersih();
            SiapIsi(false);
            tombolAwal();
            cari.setEnabled(true);
        }
    }//GEN-LAST:event_btntambahActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        // TODO add your handling code here:
         if(nip.getText().isEmpty() || namaguru.getText().isEmpty() ||tempatlahir.getText().isEmpty()|| tgllahir.getDate()==null || jenkel.getSelectedItem().equals("") ||
            cbnJabatan.getSelectedItem().equals("") || alamat.getText().isEmpty() ||  telephone.getText().isEmpty() ||  username.getText().isEmpty() || password.getText().isEmpty() ){
            JOptionPane.showMessageDialog(null, "Silahkan Lengkapi Data !!");
        }else{
            eg.setNip(nip.getText());
            eg.setNama_guru(namaguru.getText());
            eg.setTemp_lahir(tempatlahir.getText());
            eg.setTgl_lahir (sdf.format(tgllahir.getDate()));
            eg.setJ_kelamin(jenkel.getSelectedItem().toString());
            eg.setJabatan(cbnJabatan.getSelectedItem().toString());
            eg.setAlamat(alamat.getText());
            eg.setTelephone(telephone.getText());
            eg.setUsername(username.getText());
            eg.setPassword(password.getText());
               
            
        if(btntambah.getText().equalsIgnoreCase("batal")){
            if(sm.tambah(eg)==1){
                JOptionPane.showMessageDialog(null, "Simpan Data Berhasil");
            }else{
                JOptionPane.showMessageDialog(null, "Simpan Data Gagal !!");
                }
            tampil();
            }
        
        if(btnedit.getText().equalsIgnoreCase("batal")){
            if(sm.edit(eg)==1){
                JOptionPane.showMessageDialog(null, "Edit Data Berhasil");
            }else{
                JOptionPane.showMessageDialog(null, "Edit Data Gagal !!");
                }
            tampil();
            }
        
        Bersih();
        SiapIsi(false);
        btntambah.setText("Tambah");
        btnedit.setText("Edit");
        tombolAwal();
        cari.setEnabled(true);
        }
         
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        // TODO add your handling code here:
        
          eg.setNip(nip.getText());
       
        
        if(btnedit.getText().equalsIgnoreCase("edit")){
            btnedit.setText("Batal");
            SiapIsi(true);
            nip.setEnabled(false);            
            namaguru.requestFocus();
            btntambah.setEnabled(false);
            btntambah.setText("Tambah");
            btnsimpan.setEnabled(true);
            btnhapus.setEnabled(false);
            btnedit.setEnabled(true);
            btnkeluar.setEnabled(false);
            cari.setEnabled(false);
        }else{
            btnedit.setText("Edit");
            Bersih();
            SiapIsi(false);
            tombolAwal();
            cari.setEnabled(true);
        }
      
    }//GEN-LAST:event_btneditActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
       eg.setNip(nip.getText());
        
        int pesan = JOptionPane.showConfirmDialog(null, "Apakah Anda Yakin Ingin Menghapus Data Ini ??", "Konfirmasi", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(pesan == JOptionPane.YES_OPTION){
            if(sm.hapus(eg)==1){
                JOptionPane.showMessageDialog(null, "Hapus Data Berhasil");
                Bersih();
                SiapIsi(false);
                btntambah.setText("Tambah");
                tombolAwal();
                tampil();
            }else{
                JOptionPane.showMessageDialog(null, "Hapus Data Gagal !!");
            }
        }
        
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btnkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkeluarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnkeluarActionPerformed

    private void tblguruMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblguruMouseClicked
        // TODO add your handling code here:
        
        int baris = tblguru.getSelectedRow();
        nip.setText(tblguru.getModel().getValueAt(baris,0).toString());
        namaguru.setText(tblguru.getModel().getValueAt(baris, 1).toString());
        tempatlahir.setText(tblguru.getModel().getValueAt(baris, 2).toString());
        jenkel.setSelectedItem(tblguru.getModel().getValueAt(baris, 3).toString());
        cbnJabatan.setSelectedItem(tblguru.getModel().getValueAt(baris, 4).toString());
        alamat.setText(tblguru.getModel().getValueAt(baris, 5).toString());
        telephone.setText(tblguru.getModel().getValueAt(baris, 6).toString());
        entitas.Entitas_Guru us= sm.cariuser(nip.getText());
        username.setText(us.getUsername());
        password.setText(us.getPassword());
        
        SiapIsi(false);
        btnsimpan.setEnabled(false);
        btntambah.setEnabled(true);
        btntambah.setText("Batal");
        btnhapus.setEnabled(true);
        btnedit.setEnabled(true);
    }//GEN-LAST:event_tblguruMouseClicked

    private void cariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cariKeyReleased
        // TODO add your handling code here:
        String find = null;
        find = cari.getText();
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        listGuru.clear();
        listGuru=sm.cari(find);
        for (int i = 0; i < listGuru.size(); i++) {
            Object[] a=new Object[7];
            a[0]=listGuru.get(i).getNip();
            a[1]=listGuru.get(i).getNama_guru();
            a[2]=listGuru.get(i).getAlamat(); 
            a[3]=listGuru.get(i).getJ_kelamin();
            a[4]=listGuru.get(i).getTelephone();
            a[5]=listGuru.get(i).getUsername();
            a[6]=listGuru.get(i).getPassword();
            model.addRow(a);
        }  
    }//GEN-LAST:event_cariKeyReleased

    private void GsExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GsExitActionPerformed
        // Keluar
        new gui.Beranda().setVisible(true);
        dispose();
    }//GEN-LAST:event_GsExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(master_guru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(master_guru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(master_guru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(master_guru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new master_guru().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GsExit;
    private javax.swing.JTextField alamat;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnkeluar;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JButton btntambah;
    private javax.swing.JTextField cari;
    private javax.swing.JComboBox<String> cbnJabatan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jenkel;
    private javax.swing.JTextField namaguru;
    private javax.swing.JTextField nip;
    private javax.swing.JPasswordField password;
    private javax.swing.JTable tblguru;
    private javax.swing.JTextField telephone;
    private javax.swing.JTextField tempatlahir;
    private com.toedter.calendar.JDateChooser tgllahir;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
 private void tombolAwal(){
        btntambah.setEnabled(true);
        btnsimpan.setEnabled(false);
        btnedit.setEnabled(false);
        btnhapus.setEnabled(false);
        btnkeluar.setEnabled(true);
   //     kodepetugas.setEnabled(true);
    }
private void Bersih(){
        nip.setText(null);
         namaguru.setText(null);
         tempatlahir.setText(null);
         tgllahir.setDate(null);
         jenkel.setSelectedItem(null);
        cbnJabatan.setSelectedItem(null);
         alamat.setText(null);
         telephone.setText(null);
         username.setText(null);
         password.setText(null);
         
         
    }
     
    private void SiapIsi(boolean a){
        nip.setEnabled(a);
        namaguru.setEnabled(a);
        tempatlahir.setEnabled(a);
        tgllahir.setEnabled(a);
        jenkel.setEnabled(a);
        cbnJabatan.setEnabled(a);
        alamat.setEnabled(a);
        telephone.setEnabled(a);
        username.setEnabled(a);
        password.setEnabled(a);
    }
    
       private void BuatTabel(){
        model=new DefaultTableModel();
        model.addColumn("NIP");
        model.addColumn("Nama");  
        model.addColumn("Tempat lahir"); 
        model.addColumn("Tgl lahir"); 
        model.addColumn("Jenis Kelamin");
        model.addColumn("Jabatan"); 
        model.addColumn("Alamat");
        model.addColumn("Telephone");
        
        tblguru.setModel(model);
    }
        
  //untuk menampilkan data di table pasien
    private void tampil(){
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        listGuru.clear();
        listGuru=sm.tampil();
        for (int i = 0; i < listGuru.size(); i++) {
            Object[] a=new Object[10];
            a[0]=listGuru.get(i).getNip();
            a[1]=listGuru.get(i).getNama_guru();
            a[2]=listGuru.get(i).getTemp_lahir();
            a[3]=listGuru.get(i).getTgl_lahir();
            a[4]=listGuru.get(i).getJ_kelamin();
            a[5]=listGuru.get(i).getJabatan();
            a[6]=listGuru.get(i).getAlamat(); 
            a[7]=listGuru.get(i).getTelephone();
            a[8]=listGuru.get(i).getUsername();
            a[9]=listGuru.get(i).getPassword();
            model.addRow(a);
        }
    }

}
